services:
  nginx:
    image: nginx:1.25-alpine
    container_name: popeye-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - popeye-net

  backend:
    image: corqu/popeye-backend:latest
    container_name: backend
    expose:
      - "8080"
    networks:
      - popeye-net
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env

  frontend:
    image: corqu/popeye-frontend:latest
    container_name: frontend
    expose:
      - "3000"
    networks:
      - popeye-net
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: popeye-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}

      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: on-failure
    networks:
      - popeye-net

  redis:
    image: redis:alpine
    container_name: popeye-redis
    command: redis-server --requirepass ${SPRING_DATA_REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./redis/data:/data
    networks:
      - popeye-net

networks:
  popeye-net:
