version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: popeye-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: popeye
      MYSQL_USER: devuser
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD} # 일반 유저 비번

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: popeye-redis
    ports:
      - "6379:6379"