services:
  db:
    image: mysql:8.0
    container_name: popeye-db
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d # 초기 SQL 필요 시
    restart: on-failure
    environment:
      MYSQL_DATABASE: popeye
      MYSQL_USER: devuser
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD} # 일반 유저 비번
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    env_file:
      - .env.dev

  redis:
    image: redis:latest
    container_name: popeye-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: popeye-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - redis
