spring:
  application:
    name: PopeyeAndOlive

  datasource:
    url: ${SPRING_DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

popeye:
  secret-key: "my_super_secret_key_popeye_1234!"

  # Redis설정(인증 및 캐시용)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}