spring:
  datasource:
    url: ${SPRING_DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate:
        # SQL을 보기 좋게 정렬합니다.
        #format_sql: true
        # SQL의 주석(어디서 실행된 쿼리인지)을 보여줍니다.
        #use_sql_comments: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: popeye-project-content-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

popeye:
  secret-key: "my_super_secret_key_popeye_1234!"
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    client-key: ${TOSS_CLIENT_KEY}
    base-url: https://api.tosspayments.com
  encryption:
    account-secret-key: ${POPEYE_ACCOUNT_SECRET_KEY:?missing encryption key}

#logging:
#  level:
#    root: INFO
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings
